### ISSUE TITLE
doesnt run

### ISSUE THREAD

**Issue by aaron-makowski** [kusumachan/pancakeswap-listing-bot#1]
```
$ python app.py

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    bot.run()
  File "C:\Users\zenlord\Desktop\pancakeswap-listing-bot\src\core.py", line 153, in run
    self.banner()
  File "C:\Users\zenlord\Desktop\pancakeswap-listing-bot\src\core.py", line 127, in banner
    print("\033[1;36m\u2591\u2588\u2588\u2588\u2588\u2588\u2588\u2557\u2591\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2557\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2557\u2591\033[1;31m\u2588\u2588\u2588\u2588\u2588\u2557\u2591\u2591\u2588\u2588\u2588\u2588\u2588\u2557\u2591\u2588\u2588\u2557\u2591\u2591\u2588\u2588\u2557\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2557\033[0m")
  File "C:\Users\zenlord\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\Users\zenlord\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\zenlord\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\zenlord\AppData\Roaming\Python\Python37\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\zenlord\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-26: character maps to <undefined>

```
PIC version of error
https://i.gyazo.com/fba70187a4d20672d1eec7f794d170ad.png

**Comment by aaron-makowski** [comment]
K commented out the banner ascii art and it gets to the next error where you need to `pip install lxml`

**Comment by aaron-makowski** [comment]
```$ python app.py

  -[ Kusumachan | Lorosaublong | Jaka Sembung | Etc ]-
            ~ We are Nothing Without Allah ~

[+] Author    : Kusumachan
[+] Email     : bintangkusuma1337@gmail.com
[+] Instagram : @kusumachan404
[+] Github    : github.com/kusumachan/pancakeswap-listing-bot


Press Ctrl + C to exit..

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    bot.run()
  File "C:\Users\zenlord\Desktop\pancakeswap-listing-bot\src\core.py", line 162, in run
    getPair      = self.getNewPair()
  File "C:\Users\zenlord\Desktop\pancakeswap-listing-bot\src\core.py", line 109, in getNewPair
    soup            = BeautifulSoup(request.text, 'lxml')
  File "C:\Users\zenlord\AppData\Local\Programs\Python\Python37\lib\site-packages\bs4\__init__.py", line 246, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?```

**Comment by aaron-makowski** [comment]
and now it works!!
nice, small edits only
thanks for the app!!!
